[project]
name = "omni-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "googletrans==4.0.0rc1",
    "gtts>=2.5.4",
    "keyboard>=0.13.5",
    "langdetect>=1.0.9",
    "pygame>=2.6.1",
]
